# bot settings
bot_token: "5096432955:AAEvb1-awIT14uiXyL4TH_ns7uHhxFwiNK0" # support bot tok                                                                                                             en
staffchat_id: "-1001650023303" # eg. -123456789
owner_id: "1539805363"
spam_time: 5 * 60 * 1000 # time (in MS) in which user may send 5 messages

allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private

auto_close_tickets: False # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server
web_server_ssl_cert: '../src/web/ssl.crt' # Path for SSL cert
web_server_ssl_key: '../src/web/ssl.key' # Path for SSL key

dev_mode: False # Enable/disable dev mode

# customize your language
language:
    startCommandText: "ඔබව සාදරයෙන් පිළිගන්නවා! Widox පාරිභෝගික සහාය සඳහා. 🙂\n\nඅප ඔබට සහය විය යුත්තේ කෙසේද? 🙂"
    faqCommandText: ""
    helpCommandText: ""
    contactMessage: "අප හා සම්බන්ධ වීම ගැන ඔබට ස්තුතියි. අපි හැකි ඉක්මනින් පිළිතුරු දෙන්නෙමු. 🙂"
    blockedSpam: "ඔබ පසුගිය කාලය තුළ ප්‍රශ්න ගණනාවක් එවීම හේතුවෙන්, කරුණාකර සන්සුන් වී කාර්ය මණ්ඩලය ඒවා සමාලෝචනය කරන තෙක් රැඳී සිටින්න. 🙂"
    ticket: "Ticket"
    closed: "closed"
    acceptedBy: "was accepted by"
    dear: "Dear"
    regards: "මීට,"
    from: "from"
    language: "Language"
    msg_sent: "Message sent to user"
    file_sent: "File sent to user"
    usr_with_ticket: "User with ticket"
    banned: "banned"
    replyPrivate: "Reply in private"
    services: "Select a service from the list below"
    customer: "customer"
    msgForwarding: "You messages will now be forwarded to vendors of the group: "
    back: "Go back"
    whatSubCategory: "Which subcategory describes your needs the best? "
    prvChatEnded: "Private chat ended."
    prvChatOpened: "Private Chat opened with customer."
    prvChatEnd: "End Private chat"
    prvChatOpenedCustomer: "Opened private chat"
    instructionsSent: "Instructions were sent to you in private chat."
    openTickets: "Open Tickets"
    support: "Support"
    prvChatOnly: "This command can be used in private chat only."
    ticketClosed: "ඔබගේ ටිකට්පත අපගේ කාර්ය මණ්ඩලය විසින් වසා දමන ලදී. ඔබට ඕනෑම වේලාවක නව ටිකට් පතක් විවෘත කළ හැකිය."
    links: "Direct support links"
    textFirst: "පින්තුරයක් යැවීමට පෙර කරුණාකර අපට පණිවිඩයක් එවන්න එවිට අපට ඔබට වඩාත් හොඳින් සේවාව ලබා දීමට හැක. 🙂"
    ticketClosedError: "You cannot reply to a closed ticket."
    automatedReply: "This is an automated reply."
    automatedReplyAuthor: "BottyBot."
    doesntHelp: "This does not help."
    automatedReplySent: "Automated reply was send to the user."
    ticketReopened: "ටිකට් පත නැවත විවෘත කරන ලදී."

# categories: 
#  - name: "Category1"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Category2"
#    subgroups: 
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Category with no subcategories"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910" 
#  - name: "Contact"
#    msg: "Check out our Website"

    
  
